FROM  registry.cn-hangzhou.aliyuncs.com/fs-devops/maven:3-openjdk-8-slim as builder
WORKDIR /app
COPY  .  /app/
RUN mvn -B -f /app/pom.xml -s /app/settings.xml install


FROM  repository.anxinyun.cn/devops/openjdk:8-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/wvp*.jar wvp.jar
COPY --from=builder /app/src/main/resources/application-prod.yml config/application.yml

ENTRYPOINT [ "java", "-jar", "/app/wvp.jar","--spring.config.location=/app/config/application.yml" ]
